FROM centos:latest

MAINTAINER NewstarCorporation

RUN yum -y install httpd

RUN mkdir -p /var/www/html/

RUN touch index.html

COPY index.html /var/www/html/

CMD [“/usr/sbin/httpd”, “-D”, “FOREGROUND”]

EXPOSE 80



