FROM httpd:latest
#COPY ./public-html/ /usr/local/apache2/htdocs/
ADD ./httpd-custom.conf /usr/local/apache2/conf/httpd.conf
COPY htdocs /usr/local/apache2/htdocs

#FROM centos:latest
#MAINTAINER valentin
#RUN yum -y install httpd
#RUN touch index.html
#COPY index.html /var/www/html/
CMD [“/usr/sbin/httpd”, “-D”, “FOREGROUND”]

EXPOSE 80 



