apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  namespace: pod-web
spec:
  replicas: 3
  selector:
    app: pod-web
  template:
    metadata:
      labels:
        app: pod-web
        zone: prod
        version: 1
    spec:
      containers:
      - name: web-httpd
        image: doublev20/web-apache:version1
        ports:
        - containerPort: 8080
