apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: pod-web
  labels:
    zone: prod
spec:
  containers:
  - name: web-httpd
    image: doublev20/web-apache:version1
    ports:
    - containerPort: 8080
