    
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: 
  namespace: pod-web
spec:
  type: NodePort
  ports:
  - port: 8080
    NodePort: 30001
    protocol: TCP
  selector: 
    app: pod-web
